org.gradle.java.home=C:\\Java\\jdk-17

org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError

org.gradle.daemon=true
org.gradle.parallel=true

kotlin.jvm.target.validation.mode=warning
kotlin.incremental=true

android.useAndroidX=true
android.enableJetifier=true